/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeShowcase: typeof import('./../components/code-showcase.vue')['default']
    ColorGrid: typeof import('./../components/color-grid.vue')['default']
    ContactForm: typeof import('./../components/contact-form.vue')['default']
    DarkSwitch: typeof import('./../components/dark-switch.vue')['default']
    FooterBar: typeof import('./../components/footer-bar.vue')['default']
    NavBar: typeof import('./../components/nav-bar.vue')['default']
    PhotoGallery: typeof import('./../components/photo-gallery.vue')['default']
    PlaceHolder: typeof import('./../components/place-holder.vue')['default']
    PushButton: typeof import('./../components/push-button.vue')['default']
    WorkTimeline: typeof import('./../components/work-timeline.vue')['default']
  }
}
